ARG base_ros_img

FROM $base_ros_img

ARG username
ARG uid
ARG gid
ARG locale

# Fix so the user can use the webcam
RUN groupmod -g 986 video

# Creating user and group into the container and adding it to the sudoers
RUN useradd -u $uid $username
RUN groupmod -g $gid $username
RUN echo $username:$username | chpasswd
RUN echo $username 'ALL=(ALL) ALL' >> /etc/sudoers

# Setting container starting directory
WORKDIR /home/$username

# Setting bash as the default shell and vim as the default editor
ENV SHELL /bin/bash
ENV EDITOR vim

# Localization stuff
ENV TZ=$locale
# ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y \
    curl &&\
    rm -rf /var/lib/apt/lists/*
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -

# Base packages
RUN apt-get update && apt-get install -y \
    terminator \
    neovim \
    git \
    xclip \
    tmux \
    wget \
    unzip \
    iputils-ping \
    ros-pcl-msgs \
    # python3-pcl \
    # python3-pcl-msgs \
    libpcl-msgs-dev \
    libpcl-conversions-dev \
    ros-${ROS_DISTRO}-turtlebot3 \
    ros-${ROS_DISTRO}-openslam-gmapping \
    ros-${ROS_DISTRO}-navigation \
    ros-${ROS_DISTRO}-ros-control* \
    ros-${ROS_DISTRO}-control* \
    ros-${ROS_DISTRO}-moveit* &&\
    rm -rf /var/lib/apt/lists/*

# Installing tmuxinator to manage tmux project sesions
# run gem install tmuxinator

# Installing needed packages
RUN apt-get update && apt-get install -y \
    python-tk \
    ros-melodic-usb-cam* \
    ros-melodic-cv-camera \
    ros-melodic-rqt-joint-trajectory-controller \
    python-wstool \
    python-catkin-tools \
    python-pip \
    software-properties-common \
    ros-melodic-imagezero-image-transport &&\
    rm -rf /var/lib/apt/lists/*

# ICRA2022
RUN apt-get update && apt-get install -y \
    ros-melodic-socketcan-interface \
    ros-melodic-four-wheel-steering-msgs \
    python-pymodbus \
    ros-melodic-soem \
    ros-melodic-urdf-geometry-parser &&\
    rm -rf /var/lib/apt/lists/*
# RUN pip2 install -U transforms3d
RUN add-apt-repository ppa:freecad-maintainers/freecad-stable -y && apt-get update && apt install -y \
    ros-melodic-industrial-msgs \
    ros-melodic-trac-ik-kinematics-plugin \
    freecad-python2  &&\
    rm -rf /var/lib/apt/lists/*

# nvidia-docker hooks
LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}compute,utility,graphics
