ARG base_ros_img
ARG username
ARG locale

FROM $base_ros_img


# Setting container starting directory
WORKDIR /home/$username

# Setting bash as the default shell and vim as the default editor
ENV SHELL /bin/bash
ENV EDITOR vim

# Localization 
ENV TZ=$locale
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}compute,utility,graphics
