ARG base_ros_img

FROM $base_ros_img

# Base dev packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    terminator \
    neovim \
    git \
    gdb \
    xclip \
    tmux \
    wget \
    unzip \
    iputils-ping \
    python-is-python3 \
    python3-pip \
    python3-catkin-tools \
    python3-virtualenv \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

# Base ROS packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ros-${ROS_DISTRO}-moveit \
    ros-${ROS_DISTRO}-moveit-servo \
    ros-${ROS_DISTRO}-ros-control* \
    ros-${ROS_DISTRO}-ros-controllers \
    ros-${ROS_DISTRO}-ros-controllers-cartesian \
    ros-${ROS_DISTRO}-usb-cam \
    ros-${ROS_DISTRO}-video-stream-opencv \
    ros-${ROS_DISTRO}-cv-camera \
    ros-${ROS_DISTRO}-trac-ik-kinematics-plugin \
    ros-${ROS_DISTRO}-rosserial \
    ros-${ROS_DISTRO}-rosserial-arduino \
    ros-${ROS_DISTRO}-rosserial-arduino \
    ros-${ROS_DISTRO}-sensor-filters \
    ros-${ROS_DISTRO}-rqt-controller-manager \
    && rm -rf /var/lib/apt/lists/*

# Hardware specific packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ros-${ROS_DISTRO}-industrial-robot-status-interface \
    ros-${ROS_DISTRO}-scaled-joint-trajectory-controller \
    ros-${ROS_DISTRO}-speed-scaling-state-controller \
    ros-${ROS_DISTRO}-ur-msgs \
    ros-${ROS_DISTRO}-pass-through-controllers \
    ros-${ROS_DISTRO}-ur-client-library \
    ros-${ROS_DISTRO}-realsense2-camera \
    ros-${ROS_DISTRO}-mocap-optitrack \
    ros-${ROS_DISTRO}-socketcan-interface \
    ros-${ROS_DISTRO}-soem \
    && rm -rf /var/lib/apt/lists/*
