ARG base_ros_img

FROM $base_ros_img

# General packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
     setserial \
     terminator \
     neovim \
     git \
     gdb \
     xclip \
     tmux \
     wget \
     unzip \
     iputils-ping \
     python3-pip \
     python3-colcon-common-extensions \
     python3-colcon-mixin \
     python3-colcon-clean \
     python3-virtualenv \
     python3-venv \
     python3-vcstool \
    && rm -rf /var/lib/apt/lists/*
    
# C++ formating tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    clang \
    clang-tidy \
    clang-format \
    && rm -rf /var/lib/apt/lists/*
 
# Base ROS packages
 RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
	ros-${ROS_DISTRO}-moveit \
    ros-${ROS_DISTRO}-moveit-servo \
	ros-${ROS_DISTRO}-ros2-control* \
	ros-${ROS_DISTRO}-ros2-controllers* \ 	
 	ros-${ROS_DISTRO}-controller-manager \
    ros-${ROS_DISTRO}-rqt-controller-manager \
   	ros-${ROS_DISTRO}-rqt-joint-trajectory-controller \
    ros-${ROS_DISTRO}-joint-state-broadcaster \
	ros-${ROS_DISTRO}-joint-state-publisher \
	ros-${ROS_DISTRO}-joint-state-publisher-gui \	
    && rm -rf /var/lib/apt/lists/*
    
# did not install
# RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
#     ros-${ROS_DISTRO}-ros-controllers-cartesian \
#     ros-${ROS_DISTRO}-usb-cam \
#     ros-${ROS_DISTRO}-video-stream-opencv \
#     ros-${ROS_DISTRO}-cv-camera \
#     ros-${ROS_DISTRO}-trac-ik-kinematics-plugin \
#     ros-${ROS_DISTRO}-rosserial \
#     ros-${ROS_DISTRO}-rosserial-arduino \
#     ros-${ROS_DISTRO}-rosserial-arduino \
#     ros-${ROS_DISTRO}-sensor-filters \
#     && rm -rf /var/lib/apt/lists/*


# Hardware specific packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ros-${ROS_DISTRO}-ur-client-library \
    ros-${ROS_DISTRO}-realsense2-camera \
    ros-${ROS_DISTRO}-ur-msgs \
    && rm -rf /var/lib/apt/lists/*

# ros-${ROS_DISTRO}-pass-through-controllers \
# ros-${ROS_DISTRO}-mocap-optitrack \
# ros-${ROS_DISTRO}-socketcan-interface \
# ros-${ROS_DISTRO}-soem \
# ros-${ROS_DISTRO}-industrial-robot-status-interface \
# ros-${ROS_DISTRO}-scaled-joint-trajectory-controller \
# ros-${ROS_DISTRO}-speed-scaling-state-controller \

# Qt Creator
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libgl1-mesa-dev \
    ninja-build \
    libyaml-cpp-dev \
    libqtermwidget5-1-dev \
    libutf8proc-dev\
    libxcb-cursor0  \ 
    && rm -rf /var/lib/apt/lists/*

# VOSK
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3-tk \
    libasound-dev \
    libportaudio2 \
    && rm -rf /var/lib/apt/lists/*
